{% set name = "fastTSNE" %}
{% set version = "0.2.15" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ee0efa46e6d9cce1f0a5c5eb9b6eac31c1455f7d01422f1f73903ba645af9a8e

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  skip: True  # [py<35]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - numpy
    - pip
    - python
  run:
    - {{ pin_compatible('numpy') }}
    - numba >=0.38.1
    - python
    - scikit-learn >=0.20
    - scipy

test:
  imports:
    - fastTSNE

about:
  home: https://github.com/pavlin-policar/fastTSNE
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Fast, parallel implementations of tSNE
  dev_url: https://github.com/pavlin-policar/fastTSNE

extra:
  recipe-maintainers:
    - pavlin-policar
