appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: uENgR12W936ugGNPGW2E7M3dGseX84EbwEQ2eznBQvkRKEOaVWVf2L6YYu9IZvi/eVeIkj+xRNLQPyUi5/MtERaeT+4kHf/lMLluQCEAXniaNKLjSJ4iYoWANkXRAauTbYRAnXEzXJoODCmEz9nmOOkksFxwZjtCCgk/QmCm27ggfforxwLfDQtt2UfxlaylZjbsxZ6D6YQaeGc8R/y7yarSrYUlFzD5m5/0qiSdPjaHI4QRqzPK2zq15KpKs+HQBtRDfUFNNRgRzC4TKRh2eqQ2SbD++yZly3hSA5sFEx6ab5HmshMgEnm5H/98RyOSzdsZGwJRSE5j9clz06uc7S0ypJVH1ubcspDrpg+a8RMgWAOqlmWbFqwnzK37jiO63eOGwO8PhCy4BLMa37GGJ9j/7GUHDtfBZNXVrFrH0vS5MCNPu9/+3QPKbZAJgfUmy8j5YLYxh1CuSBgZ6qi7bT0V41C6QQuWzeY+gjBg3BCVulkbMHNlQDOlRwt45acHIkJ8LBheUCIX4t+bplOxVE4dO06gb90tnlKc16Y+CWfflQS0AIR47xgMZXFNbrgeewtGKZFijSXaFhZlKkj342xFRxWbwZdyboNhHU7xG6E4G6hsueB19r//z9ev3N6btRYU5tQONXNw7/f7BLCzpQ+ouS3gF1tN5zxLvfO78tU=}
